# Site Configuration
title: "Open the Science"
name: "Open Science Publishing Club"
description: "Just open the f*** science - A platform for open science publishing and collaboration #OST"
url: "https://jkobject.github.io"
baseurl: "/openthescience"
repository: "jkobject/openthescience"

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Minimal Mistakes theme configuration
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Author
author:
  name: "Open Science Publishing Club"
  avatar: # "/assets/images/bio-photo.jpg"
  bio: "Democratizing science through open publishing"
  location: "Global"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jkobject/openthescience"

# Default settings
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _research-briefs
  - scope:
      path: ""
      type: research-briefs
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Collections
collections:
  research-briefs:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# SEO
social:
  type: Organization
  name: Open Science Publishing Club
  links:
    - "https://github.com/jkobject/openthescience"

# Analytics
analytics:
  provider: false

# Site Search
search: true

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jkobject/openthescience"